### ISSUE TITLE
Crash on launch, version 0.6.0

### ISSUE THREAD

**Issue by stella-sf** [MSandro/NeoForge-Foundry-StoneBlock-Edition#20]
End of the log file:

```
[m[1;31m[13:21:34.471] [main/ERROR] [loading.LanguageLoadingProvider/LOADING]: Missing language javafml version [48,) wanted by Philips-Ruins1.20.4-1.0.jar, found 2.0 
[m[1;31m[13:21:34.472] [main/ERROR] [loading.LanguageLoadingProvider/LOADING]: Missing language javafml version [46,) wanted by grindenc-forge-1.20.x-v2.0.jar, found 2.0 
[m[1;31m[13:21:34.473] [main/ERROR] [loading.LanguageLoadingProvider/LOADING]: Missing language javafml version [36,) wanted by DontClearChatHistory-1.jar, found 2.0 
[m[1;31m[13:21:34.473] [main/ERROR] [loading.LanguageLoadingProvider/LOADING]: Missing language javafml version [46,) wanted by MyServerIsCompatible-1.20-1.0.jar, found 2.0 
[m!![Fatal]!Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.module.ResolutionException: Modules rhino.lib.SNAPSHOT and rhino export package dev.latvian.mods.unit.operator to module woodentoolsremoved
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Process exited with code 2.
```

**Comment by stella-sf** [comment]
Resolved: I had enabled the JSON Things mod which was marked as "optional", but since it seems to have been phased out with 0.6.0, I tried disabling it and that fixes the issue and loads the game properly.
